### ISSUE TITLE
Error in webpack config

### ISSUE THREAD

**Issue by Victory** [TobiahRex/nj2jp#5]
`bundle.js` in dist is 18MB making load times of the site too long. [see bundle.js](https://github.com/TobiahRex/nj2jp/blob/master/dist/bundle.js)

The bundle is loaded when visiting https://nj2jp.herokuapp.com/

Cheers,
  ~ DfhuVictory

**Comment by TobiahRex** [comment]
Thanks for the post. Its a huge bundle file no doubt, and while i know it contributes to a slow load, heroku dynos are 50% of the reason its slow.  Never the less i do plan on optimizing the webpack production config settings. Thanks again.

**Comment by TobiahRex** [comment]
Thanks again for the post Victory. I can't honestly say I was thinking about the bundle size since I was deploying to a free tier Heroku server.  My thinking was, they've always had super slow spin ups in my previous experiences with them but now that the bundle has a sourcemap  its total is @ <800kb and Splash is only at 176kb - WAY FASTER.  😳  So this is me officially falling on my sword. Thanks again 👍
